# ===================================
#  Form Behavior Config
# ===================================

name: backend::lang.backend_preferences.menu_label
form: ~/modules/backend/models/preferences/fields.yaml
modelClass: Backend\Models\Preferences
defaultRedirect: system/settings
