language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - nightly

matrix:
  allow_failures:
    - php: nightly

sudo: false

install:
  - composer self-update
  - travis_retry composer install --no-interaction --prefer-source

before_script: git reset --hard HEAD

stages:
  - "Linting"
  - "Tests"
  - "Code Quality"

jobs:
  include:
    - stage: "Linting"
      script: ./vendor/bin/parallel-lint $(git diff-tree --no-commit-id --name-only -r develop..HEAD | grep ".php")
    - stage: "Tests"
      script: ./vendor/bin/phpunit
    - stage: "Code Quality"
      php: 7.1
      script: ./vendor/bin/phpcs --colors -nq --report="full" $(git diff-tree --no-commit-id --name-only -r develop..HEAD)
