# ===================================
#  List Behavior Config
# ===================================

title: backend::lang.access_log.menu_label
list: ~/modules/backend/models/accesslog/columns.yaml
modelClass: Backend\Models\AccessLog
noRecordsMessage: backend::lang.list.no_records
recordsPerPage: 30
showSetup: true

toolbar:
    buttons: list_toolbar
    search:
        prompt: backend::lang.list.search_prompt

filter: config_filter.yaml
