server {
    listen 80;
    listen [::]:80;
    server_name _;

    root /app;
    index index.php;
    charset utf-8;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";

    location = /health {
        access_log off;
        add_header Content-Type text/plain;
        return 200 'ok';
    }

    location / {
        # Let October CMS handle everything by default.
        # The path not resolved by October CMS router will return October CMS's 404 page.
        # Everything that does not match with the allowlist below will fall into this.
        rewrite ^/.*$ /index.php last;
    }

    # Pass the PHP scripts to FastCGI server
    location ~ ^/index\.php {
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $realpath_root/index.php;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
        fastcgi_hide_header X-Powered-By;
    }

    # Allowlist
    location ~ ^/(favicon\.ico|sitemap\.xml|robots\.txt|humans\.txt) { try_files $uri /index.php; }

    # Block all .dotfiles except well-known
    location ~ /\.(?!well-known).* { deny all; }
    
    ## Static Files
    location ~ ^/storage/app/(uploads/public|media|resources) { try_files $uri 404; }
    location ~ ^/storage/temp/public { try_files $uri 404; }
    location ~ ^/modules/.*/(assets|resources) { try_files $uri 404; }
    location ~ ^/modules/.*/(behaviors|widgets|formwidgets|reportwidgets)/.*/(assets|resources) { try_files $uri 404; }
    location ~ ^/plugins/.*/.*/(assets|resources) { try_files $uri 404; }
    location ~ ^/plugins/.*/.*/(behaviors|reportwidgets|formwidgets|widgets)/.*/(assets|resources) { try_files $uri 404; }
    location ~ ^/themes/.*/(?:assets|resources) { try_files $uri 404; }
}
