# ===================================
#  List Behavior Config
# ===================================

title: system::lang.email_templates.menu_label
list: @/modules/system/models/emailtemplate/columns.yaml
modelClass: System\Models\EmailTemplate
recordUrl: system/emailtemplates/update/:id
noRecordsMessage: backend::lang.list.no_records
recordsPerPage: 20
showSetup: false

toolbar:
    buttons: list_templates_toolbar
    search:
        prompt: backend::lang.list.search_prompt