# ===================================
#  List Behavior Config
# ===================================

title: system::lang.request_log.menu_label
list: ~/modules/system/models/requestlog/columns.yaml
modelClass: System\Models\RequestLog
recordUrl: system/requestlogs/preview/:id
noRecordsMessage: backend::lang.list.no_records
recordsPerPage: 30
showSetup: true
showCheckboxes: true
defaultSort:
    column: count
    direction: desc

toolbar:
    buttons: list_toolbar
    search:
        prompt: backend::lang.list.search_prompt