<?php

return [

    /*
     * Laravel aliases
     */
    // 'App'             => 'Illuminate\Support\Facades\App',
    // 'Artisan'         => 'Illuminate\Support\Facades\Artisan',
    // 'Cache'           => 'Illuminate\Support\Facades\Cache',
    // 'ClassLoader'     => 'Illuminate\Support\ClassLoader',
    // 'Controller'      => 'Illuminate\Routing\Controller',
    // 'Cookie'          => 'Illuminate\Support\Facades\Cookie',
    // 'Crypt'           => 'Illuminate\Support\Facades\Crypt',
    // 'DB'              => 'Illuminate\Support\Facades\DB',
    // 'Eloquent'        => 'Illuminate\Database\Eloquent\Model',
    // 'Event'           => 'Illuminate\Support\Facades\Event',
    // 'Hash'            => 'Illuminate\Support\Facades\Hash',
    // 'HTML'            => 'Illuminate\Support\Facades\HTML',
    // 'Input'           => 'Illuminate\Support\Facades\Input',
    // 'Lang'            => 'Illuminate\Support\Facades\Lang',
    // 'Log'             => 'Illuminate\Support\Facades\Log',
    // 'Mail'            => 'Illuminate\Support\Facades\Mail',
    // 'Paginator'       => 'Illuminate\Support\Facades\Paginator',
    // 'Password'        => 'Illuminate\Support\Facades\Password',
    // 'Queue'           => 'Illuminate\Support\Facades\Queue',
    // 'Redirect'        => 'Illuminate\Support\Facades\Redirect',
    // 'Redis'           => 'Illuminate\Support\Facades\Redis',
    // 'Request'         => 'Illuminate\Support\Facades\Request',
    // 'Response'        => 'Illuminate\Support\Facades\Response',
    // 'Route'           => 'Illuminate\Support\Facades\Route',
    // 'Schema'          => 'Illuminate\Support\Facades\Schema',
    // 'Session'         => 'Illuminate\Support\Facades\Session',
    // 'URL'             => 'Illuminate\Support\Facades\URL',
    // 'Validator'       => 'Illuminate\Support\Facades\Validator',
    // 'View'            => 'Illuminate\Support\Facades\View',
    // 'Form'            => 'Illuminate\Support\Facades\Form',

    'App'       => 'Illuminate\Support\Facades\App',
    'Artisan'   => 'Illuminate\Support\Facades\Artisan',
    // 'Auth'      => 'Illuminate\Support\Facades\Auth',
    // 'Blade'     => 'Illuminate\Support\Facades\Blade',
    'Bus'       => 'Illuminate\Support\Facades\Bus',
    'Cache'     => 'Illuminate\Support\Facades\Cache',
    // 'Config'    => 'Illuminate\Support\Facades\Config',*
    'Cookie'    => 'Illuminate\Support\Facades\Cookie',
    'Crypt'     => 'Illuminate\Support\Facades\Crypt',
    'DB'        => 'Illuminate\Support\Facades\DB',
    'Eloquent'  => 'Illuminate\Database\Eloquent\Model',
    'Event'     => 'Illuminate\Support\Facades\Event',
    // 'File'      => 'Illuminate\Support\Facades\File',*
    'Hash'      => 'Illuminate\Support\Facades\Hash',
    'Input'     => 'Illuminate\Support\Facades\Input',
    // 'Inspiring' => 'Illuminate\Foundation\Inspiring',
    'Lang'      => 'Illuminate\Support\Facades\Lang',
    'Log'       => 'Illuminate\Support\Facades\Log',
    'Mail'      => 'Illuminate\Support\Facades\Mail',
    'Password'  => 'Illuminate\Support\Facades\Password',
    'Queue'     => 'Illuminate\Support\Facades\Queue',
    'Redirect'  => 'Illuminate\Support\Facades\Redirect',
    'Redis'     => 'Illuminate\Support\Facades\Redis',
    'Request'   => 'Illuminate\Support\Facades\Request',
    'Response'  => 'Illuminate\Support\Facades\Response',
    'Route'     => 'Illuminate\Support\Facades\Route',
    'Schema'    => 'Illuminate\Support\Facades\Schema',
    'Session'   => 'Illuminate\Support\Facades\Session',
    'Storage'   => 'Illuminate\Support\Facades\Storage',
    'URL'       => 'Illuminate\Support\Facades\URL',
    'Validator' => 'Illuminate\Support\Facades\Validator',
    'View'      => 'Illuminate\Support\Facades\View',
    'Form'      => 'Illuminate\Support\Facades\Form',

    /*
     * October aliases
     */
    'Model'           => 'October\Rain\Database\Model',
    'Block'           => 'October\Rain\Support\Facades\Block',
    'File'            => 'October\Rain\Support\Facades\File',
    'Config'          => 'October\Rain\Support\Facades\Config',
    'Seeder'          => 'October\Rain\Database\Updates\Seeder',
    'Flash'           => 'October\Rain\Support\Facades\Flash',
    'Http'            => 'October\Rain\Support\Facades\Http',
    'Str'             => 'October\Rain\Support\Facades\Str',
    'Markdown'        => 'October\Rain\Support\Facades\Markdown',
    'Yaml'            => 'October\Rain\Support\Facades\Yaml',
    'DbDongle'        => 'October\Rain\Support\Facades\DbDongle',
    'Backend'         => 'Backend\Facades\Backend',
    'BackendMenu'     => 'Backend\Facades\BackendMenu',
    'BackendAuth'     => 'Backend\Facades\BackendAuth',
    'SystemException'      => 'October\Rain\Exception\SystemException',
    'ApplicationException' => 'October\Rain\Exception\ApplicationException',
    'ValidationException'  => 'October\Rain\Exception\ValidationException',
];
