# ===================================
#  Form Behavior Config
# ===================================

name: backend::lang.user.group.name
form: ~/modules/backend/models/usergroup/fields.yaml
modelClass: Backend\Models\UserGroup
defaultRedirect: backend/usergroups

create:
    redirect: backend/usergroups/update/:id
    redirectClose: backend/usergroups

update:
    redirect: backend/usergroups
    redirectClose: backend/usergroups
