<backend-inspector-control-text
    v-if="control.type == 'string' || control.type == 'text'"
    :obj="obj"
    :parent-obj="parentObj"
    :control="control"
    :control-id="controlEditorId"
    :splitter-data="splitterData"
    :panel-update-data="panelUpdateData"
    :layout-update-data="layoutUpdateData"
    :inspector-preferences="inspectorPreferences"
    ref="editor"
    @focus="onEditorFocus"
    @blur="onEditorBlur"
    @invalid="onEditorInvalid"
    @valid="onEditorValid"
></backend-inspector-control-text>

<backend-inspector-control-dropdown
    v-if="control.type == 'dropdown'"
    :obj="obj"
    :parent-obj="parentObj"
    :control="control"
    :control-id="controlEditorId"
    :inspector-preferences="inspectorPreferences"
    ref="editor"
    @focus="onEditorFocus"
    @blur="onEditorBlur"
    @invalid="onEditorInvalid"
    @valid="onEditorValid"
></backend-inspector-control-dropdown>

<backend-inspector-control-autocomplete
    v-if="control.type == 'autocomplete'"
    :obj="obj"
    :control="control"
    :control-id="controlEditorId"
    :inspector-preferences="inspectorPreferences"
    ref="editor"
    @focus="onEditorFocus"
    @blur="onEditorBlur"
    @invalid="onEditorInvalid"
    @valid="onEditorValid"
></backend-inspector-control-autocomplete>

<backend-inspector-control-checkbox
    v-if="control.type == 'checkbox'"
    :obj="obj"
    :control="control"
    :control-id="controlEditorId"
    :inspector-preferences="inspectorPreferences"
    ref="editor"
    @focus="onEditorFocus"
    @blur="onEditorBlur"
    @invalid="onEditorInvalid"
    @valid="onEditorValid"
></backend-inspector-control-checkbox>

<backend-inspector-control-table
    v-if="control.type == 'table'"
    :obj="obj"
    :parent-obj="parentObj"
    :control="control"
    :control-id="controlEditorId"
    :inspector-preferences="inspectorPreferences"
    ref="editor"
    @hidebottomborder="bottomBorderHidden = true"
    @hidefullwidthlabel="controlLabelHidden = true"
></backend-inspector-control-table>

<backend-inspector-control-object
    v-if="control.type == 'object'"
    :obj="obj"
    :parent-obj="parentObj"
    :control="control"
    :control-id="controlEditorId"
    :inspector-preferences="inspectorPreferences"
    :splitter-data="splitterData"
    :inspector-unique-id="inspectorUniqueId"
    :depth="depth"
    :panel-update-data="panelUpdateData"
    :layout-update-data="layoutUpdateData"
    ref="editor"
    @hidefullwidthlabel="controlLabelHidden = true"
    @hidebottomborder="bottomBorderHidden = true"
></backend-inspector-control-object>

<backend-inspector-control-set
    v-if="control.type == 'set'"
    :obj="obj"
    :parent-obj="parentObj"
    :control="control"
    :control-id="controlEditorId"
    :inspector-preferences="inspectorPreferences"
    :splitter-data="splitterData"
    :inspector-unique-id="inspectorUniqueId"
    :depth="depth"
    :panel-update-data="panelUpdateData"
    :layout-update-data="layoutUpdateData"
    ref="editor"
    @hidefullwidthlabel="controlLabelHidden = true"
    @hidebottomborder="bottomBorderHidden = true"
></backend-inspector-control-set>

<backend-inspector-control-objectlist
    v-if="control.type == 'objectList'"
    :obj="obj"
    :parent-obj="parentObj"
    :control="control"
    :control-id="controlEditorId"
    :inspector-preferences="inspectorPreferences"
    :splitter-data="splitterData"
    :inspector-unique-id="inspectorUniqueId"
    :depth="depth"
    :panel-update-data="panelUpdateData"
    :layout-update-data="layoutUpdateData"
    ref="editor"
    @hidefullwidthlabel="controlLabelHidden = true"
    @hidebottomborder="bottomBorderHidden = true"
></backend-inspector-control-objectlist>

<backend-inspector-control-objectlist-records
    v-if="control.type == 'objectListRecords'"
    :obj="obj"
    :parent-obj="parentObj"
    :control="control"
    :control-id="controlEditorId"
    :inspector-preferences="inspectorPreferences"
    :splitter-data="splitterData"
    :inspector-unique-id="inspectorUniqueId"
    :depth="depth"
    :panel-update-data="panelUpdateData"
    :layout-update-data="layoutUpdateData"
    ref="editor"
    @hidefullwidthlabel="controlLabelHidden = true"
    @hidebottomborder="bottomBorderHidden = true"
    @inspectorcommand="$emit('inspectorcommand', $event)"
></backend-inspector-control-objectlist-records>

<backend-inspector-control-dictionary
    v-if="control.type == 'dictionary'"
    :obj="obj"
    :parent-obj="parentObj"
    :control="control"
    :control-id="controlEditorId"
    :inspector-preferences="inspectorPreferences"
    :splitter-data="splitterData"
    :inspector-unique-id="inspectorUniqueId"
    :depth="depth"
    :panel-update-data="panelUpdateData"
    :layout-update-data="layoutUpdateData"
    ref="editor"
    @hidefullwidthlabel="controlLabelHidden = true"
    @hidebottomborder="bottomBorderHidden = true"
></backend-inspector-control-dictionary>

<backend-inspector-control-mediafinder
    v-if="control.type == 'mediafinder'"
    :obj="obj"
    :parent-obj="parentObj"
    :control="control"
    :control-id="controlEditorId"
    :splitter-data="splitterData"
    :panel-update-data="panelUpdateData"
    :layout-update-data="layoutUpdateData"
    :inspector-preferences="inspectorPreferences"
    ref="editor"
    @focus="onEditorFocus"
    @blur="onEditorBlur"
    @invalid="onEditorInvalid"
    @valid="onEditorValid"
></backend-inspector-control-mediafinder>