# ===================================
#  List Behavior Config
# ===================================

title: system::lang.event_log.menu_label
list: ~/modules/system/models/eventlog/columns.yaml
modelClass: System\Models\EventLog
recordUrl: system/eventlogs/preview/:id
noRecordsMessage: backend::lang.list.no_records
recordsPerPage: 30
showSetup: true
showCheckboxes: true

toolbar:
    buttons: list_toolbar
    search:
        prompt: backend::lang.list.search_prompt

filter: config_filter.yaml
