name: Tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  frontendTests:
    runs-on: ubuntu-latest
    name: JavaScript
    steps:
      - name: Checkout changes
        uses: actions/checkout@v1
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 8
      - name: Install Node dependencies
        run: npm install
      - name: Run tests
        run: npm run test
